### ISSUE TITLE
We should not use the demo app to get token

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/speech-ios-sdk#1]
Getting a token from https://speech-to-text-demo.mybluemix.net/token will be rate limited and it should not be advertised as the way to get token. Users can use that token and use the service for free... We need to remove this ASAP.

**Comment by daniel-bolanos** [comment]
Ok, I removed it in both sdks. But please be aware that the hole is already there since both the TTS and STT demos are open source and the url to get the token for free is there for everybody to see. I brough this up long ago.

**Comment by germanattanasio** [comment]
I need to add rate-limiting to the demos :(

**Comment by germanattanasio** [comment]
thanks for the update!
