### ISSUE TITLE
Unexpected characters sent to TTS cause it to stop mid playback

### ISSUE THREAD

**Issue by scprotz** [watson-developer-cloud/speech-ios-sdk#14]
I had some HTML that was sent directly to TTS.  The &quot; caused TTS to stop at that point.  Solution was to escape or replace the odd characters.

**Comment by germanattanasio** [comment]
I think the library should handle this so I will keep this open

**Comment by mihui** [comment]
TTS supports SSML and plaintext as input, this should be handled on app level:

https://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/text-to-speech/api/v1/#introduction
http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/text-to-speech/SSML.shtml
