### ISSUE TITLE
Does not return processed results when library is imported (React Native)

### ISSUE THREAD

**Issue by garrettmaring** [watson-developer-cloud/speech-ios-sdk#15]
The UI of my app uses React Native, but all of the Watson Speech-To-Text is in Objective-C.  On button press the app correctly logs that I've connected to the Watson server, and that the state is "listening". When speaking into the application nothing is returned in the results as is in the demo app or logged.

Steps to recreate:
- Initialize a React Native project `$ react-native init test_project`
- Add the following libraries by going to build phase and clicking '+':
      • CFNetwork.framework 
  • AudioToolbox.framework 
  • AVFoundation.framework 
  • Quartzcore.framework 
  • CoreAudio.framework 
  • Security.framework 
  • Foundation.framework 
  • libicucore.tbd
    •       watsonsdk.framework (dragged and drop from unzipping file from cloned speech-ios-sdk repo)
- Build a React Bridge module as an NSObject
- Create initialize function similar to the watsonsdktest initialize/config STT
- Create listen function

Both of the above are copied from the WatsonSDKtest Speech-To-Text example. Here they reside inside an NSObject and the methods are being invoked from React Native.
- Create a button in React Native to trigger the Listen function in Objective-C (using RCTBridgeModule).
- Run and press button

You will then see NSLogs like the sample app including confirmation of server connection as well as state update, except that after the state is "listening", no results are returned or logged.

Could the issue be on React Native's end? Or that these methods are being called from a Bridge Module as an NSObject as opposed to a ViewController?

**Comment by geraldarthurdavis** [comment]
<img width="1184" alt="screen shot 2015-10-16 at 3 56 10 pm" src="https://cloud.githubusercontent.com/assets/8270120/10555058/7d648b46-741e-11e5-9c16-de7daf47e367.png">

<img width="941" alt="screen shot 2015-10-16 at 3 56 23 pm" src="https://cloud.githubusercontent.com/assets/8270120/10555059/8275ad9a-741e-11e5-8114-f0b7bbad75c3.png">

**Comment by gtona** [comment]
@garrettmaring I just started looking into integrating the Watson Speech-to-tech sdk into my React Native app and having the same issue. Were you able to figure this out?

**Comment by germanattanasio** [comment]
did you guys tried with the https://github.com/watson-developer-cloud/ios-sdk ?

**Comment by zunair-syed** [comment]
@garrettmaring @gtona Were you guys able to find a solution? I'm trying to build a react-native app and trying to have Watson STT and TTS

**Comment by kognate** [comment]
You might want to try the node SDK for react native.  You can install it via npm.

**Comment by zunair-syed** [comment]
I'm certain the node SDK won't work. Even if it would work, it doesn't solve the major issue which is getting native microphone and speaker working, which could be done by integrating Watson iOS or Android SDKs.
