### ISSUE TITLE
Fix the differences between the README, the example, and the classes provided in the AAR

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/speech-ios-sdk#18]
I got an email with useful feedback regarding the discrepancy between our README and the classes that we provide in the sdk.

> In instantiating the `SpeechToText` instance, the README uses `new SpeechConfiguration()`.  This is also what the example application does.  However, the AAR does not contain the `SpeechConfiguration` class.  The method signature implied by the README is `initWithContext(URI, Context, SpeechConfiguration)`.  
> 
> The method signature in the AAR is `initWithContext(URI, Context, boolean)`.  The boolean here represents `isUsingVad` but the documentation makes no mention of what "Vad" is, how it should be used, etc.
> 
> This is one of the inconsistencies I've found in the SDK.  The very next step in the README is `setCredentials(username, password)` - but in the AAR does not contain this method.  Is it instead broken out to two methods, one for user and one for password.
> 
> It goes on and on like this (`ISpeechDelegate` vs `SpeechDelegate`, `setModel(String)` which does not exist at all in the AAR, etc.).

**Comment by daniel-bolanos** [comment]
@germanattanasio , I think this feedback corresponds to the Android SDK not the iOS one. Can you please check.

thank you

Dani
