### ISSUE TITLE
Enable bitcode

### ISSUE THREAD

**Issue by garrettmaring** [watson-developer-cloud/speech-ios-sdk#20]
We are using your SDK and want to 'Enable Bitcode'. Is there a reason your framework has Bitcode disable/'no'?

**Comment by pacificanfog0** [comment]
I am running into a similar/same issue:

`watsonsdk.framework/watsonsdk(AuthConfiguration.o)` does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
