### ISSUE TITLE
Can't find libicucore.dylib in iOS standard frameworks

### ISSUE THREAD

**Issue by rajohns08** [watson-developer-cloud/speech-ios-sdk#21]
The README states:

> Some additional iOS standard frameworks must be added.
> 1. Select your project in the Xcode file explorer and open the "Build Phases" tab. Expand the "Link Binary With Libraries" section and click the + icon
> 2. Add the following frameworks
> - ...
> - **libicucore.dylib**

but I don't see `libicucore.dylib`. Instead I see `libicucore.tbd`. I am using Xcode 7.1:

![screen shot 2015-11-04 at 11 23 20 am](https://cloud.githubusercontent.com/assets/2711642/10946581/91d20800-82e8-11e5-8044-6fb69632986b.png)

Are these interchangeable? And could the README be updated to reflect the actual extension seen if that's the case?

**UPDATE**: It seems that `.tbd` is the successor to `.dylib` according to http://stackoverflow.com/questions/31450690/why-xcode-7-shows-tbd-instead-of-dylib

**Comment by nfriedly** [comment]
Hi @rajohns08, thanks for pointing that out, you're correct that libicucore.tbd replaced libicucore.dylib. I just tested it and updated the readme appropriately.

**Comment by w-i-n-s** [comment]
25 march 2016, issue did closed
Work without cocoapods according [official Mixpanel guide](https://mixpanel.com/blog/2014/09/30/integrating-the-mixpanel-ios-sdk-without-cocoapods)
and issue was solve after adding libicucore.tbd
