### ISSUE TITLE
Using the SDK in a Swift Project with Cocoa Pods

### ISSUE THREAD

**Issue by idea360** [watson-developer-cloud/speech-ios-sdk#22]
Per the setup instructions in the common error section I'm getting the error: 

```
undef: _utf8_nextCharSafeBody
Undefined symbols for architecture x86_64:
    "_utf8_nextCharSafeBody", referenced from:
    _validate_dispatch_data_partial_string in watsonsdk(SRWebSocket.o)
 ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I am also using Pods to install some other frameworks to use, is the install different for Pod based project vs non pod based project? Or maybe there is some trick to use it with Cocoa Pods?

**Comment by jpatrickmc** [comment]
This may help https://www.ng.bluemix.net/docs/starters/mobilefirst/gettingstarted/existingproject.html#setup_sdk_cocoapods

**Comment by idea360** [comment]
Thanks, problem was related to my build settings. Make sure to have i386 and x86_64 in your valid architectures.
