### ISSUE TITLE
ignoring debug info with an invalid version (600056001)

### ISSUE THREAD

**Issue by jpatrickmc** [watson-developer-cloud/speech-ios-sdk#23]
Running Xcode Version 7.1.1 (7B1005), I'm seeing 133 warnings in my project within the watsonsdk. I'd like to get rid of these. Two examples follow:

ld: warning: ignoring debug info with an invalid version (600056001) in /Users/jpatrickmc/Desktop/SpeechTest/watsonsdk.framework/watsonsdk(bands.o)
ld: warning: ignoring debug info with an invalid version (600056001) in /Users/jpatrickmc/Desktop/SpeechTest/watsonsdk.framework/watsonsdk(celt.o)

**Comment by kingabird** [comment]
xcode 7.1.1, me too.
