### ISSUE TITLE
Quick Start Swift Setup Guide

### ISSUE THREAD

**Issue by KeyOnTech** [watson-developer-cloud/speech-ios-sdk#25]
Quick Start Swift Setup Guide to getting started with IBM Bluemix Watson iOS SDK

I am writing this to help anyone who is going through or went through what I did to get the example up and running.

To get the iOS Swift SPEECH TO TEXT and TEXT TO SPEECH working following these instructions, I am writing them as I am doing them as of 3-2-2016.

Once you've created your IBM BlueMix account and setup your service accounts you are all set (see my steps below).

https://github.com/watson-developer-cloud/speech-android-sdk/issues/7

Create a new Xcode project
Swift Project
download the project zip says DEPRECATED but we found it gave us live recording...

https://github.com/watson-developer-cloud/speech-ios-sdk

On your Mac open your downloads folder there will be a watsonsdk.framwork.zip file.
Dbl click this file 
A folder will be created

Go back to Xcode
on the top left you will see your project name
Right Click add New Group
call it Frameworks

This step is important
NOW YOUR PROJECT IS CREATED, IN FINDER OPEN THIS FOLDER
you will see the project folder and the .xcodeproj  file...
Copy the WatsonSDK.framework file / folder you downloaded into this same directory...
Now you have 3 things an xcodeproj file, a project folder, and the watsonsdk.framework 
Now you can proceed...  
My Xcode experience is NOT advanced so this was an issue where the following steps would not work without this...

Now Drag the WatsonSDK.framwork folder/ file you just added to your project folder to the Frameworks folder in your Xcode project

Uncheck copy items if needed
Select create folder references
Check add to targets project name
Click Finish

Now we'll add the iOS Frameworks we need for the project

Click your Project on the top left
Go to General
On bottom under Linked Frameworks and Libraries
click the + and add all the headers in Step 2 of the instructions found here

https://github.com/watson-developer-cloud/speech-ios-sdk

Now add the Objective C header bridge file

Your Project is on the top left, below that is a folder with your project name again
Right Click this folder select New File
Select iOS Header File
Name it

watsonsdk.h

check the box saying add to target for your project

Open this file
Under the preset code and above the #endif line...
add the #imports  in Step 2 of the instructions Include Headers found here

https://github.com/watson-developer-cloud/speech-ios-sdk

Now lets add the header to the project
Click your Project on the top left
Go to Build Settings
Search for Swift Compiler - Code Generation   --   Objective-C Briding Header  --  Debug & Release 
Type in the project name/watsonsdk.h   or what ever you named the bridging  file...
test/watsonsdk.h

Now lets confirm everything is working

Go to the ViewController.swift
Under ViewDidLoad add
let sit:SpeechToText = SpeechToText();

Now run and confirm it Builds Successfully

Thats it for the setup now you can use the library

Now you can add a conf:STTConfiguration ...
set the basicAuthUsername
set the basicAuthPassword
set the audioCodec

and SpeechToText.init...

This will setup the app and prepare you to follow what is on the start up guide of the instructions found here

https://github.com/watson-developer-cloud/speech-ios-sdk

Hope this helps new users get started.

**Comment by germanattanasio** [comment]
@KeyOnTech thanks for the insights, can you make this to be a pull request ?
