### ISSUE TITLE
Target iOS 8.0 or up?

### ISSUE THREAD

**Issue by nacho4d** [watson-developer-cloud/speech-ios-sdk#28]
I know this is deprecated and you guys suggest to use the new [iOS-SDK](https://github.com/watson-developer-cloud/ios-sdk). However, in my opinion this objc-c based SDK is ideal to integrate into Cordova. Because:
- It is Objective-C, same as all Cordova iOS stuff
- It has very few dependencies (in comparison with the new [iOS-SDK](https://github.com/watson-developer-cloud/ios-sdk) )

If you are ok, I can make a pull request to upgrade the target from ancient 6.1 to 8.0 so we can use frameworks, which would make Cordova dev's life even easier :)

**Comment by nacho4d** [comment]
(PS: I am NOT suggesting to make this un-deprecated. Just saying that while it is been deprecated it is highly usable code 👍  )

**Comment by germanattanasio** [comment]
Go a head

**Comment by daniel-bolanos** [comment]
@nacho4d @germanattanasio , if this is highly usable code, not available in any other project, maybe we should undeprecate. Why would this need to be deprecated? Can this coexist with the "official" iOS SDK?

**Comment by germanattanasio** [comment]
this is for a small set of users using objective c. It can be achieved using the new ios-SDK and a wrapper for Objective-C.

**Comment by nacho4d** [comment]
@daniel-bolanos @germanattanasio IMO I don't think objc people is a small set. Most of relative old enterprise apps, cordova apps, etc are in objc. Objc still has a big advantage, new versions of the compiler must be source-code compatible. Swift breaks source-code compatibility every release making it a nigthmare for cases when releases are NOT often (twice a year for example). For that reason, In case of Cordova apps, I prefer to have objc code rather than have a wrapper of swift.

BTW, here is the framework pull request 😄  https://github.com/watson-developer-cloud/speech-ios-sdk/pull/30

**Comment by daniel-bolanos** [comment]
@nacho4d , do you think it is worth un-deprecating this? If we plan to continue supporting this repo because it covers important use cases not covered by the official ios SDK then I think we need to un-deprecate, if we plan to somehow provide the functionality this SDK provides in the official watson-ios-sdk, then deprecation makes sense.

Dani

**Comment by germanattanasio** [comment]
@daniel-bolanos I guess this is related to the language and not the functionality. We already looked at the functionality and the `ios-sdk` has all the features this project has and more. I see the value in having an Objective-C project. I also know that during the WWDC conference there was almost nothing about Objective-C and everything was around Swift.

**Comment by daniel-bolanos** [comment]
Yes @germanattanasio, this is probably all about the language, nonetheless I wonder if providing support for objective-c would justify undeprecating this project.

**Comment by germanattanasio** [comment]
I'm worried that if we un-deprecate the project then people will expect from us to support it. If a client starts using this and they hit an error we will have to fix it and my team doesn't have the skills for this.

**Comment by nacho4d** [comment]
@germanattanasio @daniel-bolanos The word "deprecated" sounds to me like "We are not developing this any more, you are at your own". So I will handle with caution. Which is exactly what @germanattanasio wants (I believe).

In reality, this projects seems to be updated once in a while and some bugs are being solved. So it is **not** abandoned 👍 . Maybe there is a better wording than "Deprecated". IMHO I imagine something like: _This project is here as is. Because we have a more complete and shiny sdk [ios-sdk](https://github.com/watson-developer-cloud/ios-sdk) we might not fix issues here right away._

BTW, if you have some specific tasks/issues so solve I am glad to help, just @ me :]

**Comment by mihui** [comment]
@nacho4d now the encoded data (the data is being written to socket) can't be decoded by current TTS decoding code, also there is no streaming feature of TTS, would you help on it? 

Thanks.

**Comment by nacho4d** [comment]
@mihui  I just checked the sample objective-c app. It looks it is working fine here. (I have tried STT and TSS, both in japanese and english). The only difference I find is that I am hard-coding my credentials.

Do you have any messages in the logs or something?

**Comment by mihui** [comment]
@nacho4d no, they works just fine, let me explain that a little more: 

There are two other things if you're interested, I also should be working on those too, but I'm now focusing on Android Speech SDK repo: 
- implement decoding recorded and encoded audio data in ogg/opus: if I intercept the encoded audio data which is recorded and being written in socket, and save it locally (for playback), I can't decode it or play by using current decoding method. This is useful when there is a need for playback or verify what  the user was speaking and sent out, and storing minimum size of audio data
- implement Text-to-Speech streaming (decode and play while downloading): currently it only decodes and plays the audio data after fully downloading it, if it's a long phrase, the user needs to wait for more time

**Comment by nacho4d** [comment]
@mihui I see, there are new features you are trying to implement ;-]

I didn't understand the first one but regarding the second one I think got it. I will try to make time on July and try to implement it... (This week I have a demo app to complete I am quite full). I would recommend to open a couple of issues and keep conversation there. 

This thread that was about targeting 8.0 is IMO resolved and I think should be closed if other people are ok with it.

**Comment by mihui** [comment]
@nacho4d yes, 1st one is actually relevant to the 2nd. The idea is to save the audio data locally for what you have recorded and encoded, to hear what you just said/sent to STT service. 

There will be a need to validate wrong transcription, for instance, if Watson Speech Service returns a transcript that I am not expected, I want to know what I have said, or maybe the SDK itself did something wrong. :)

It's just an idea in my mind, I'm not sure if we should open one issue for it, but the 2nd one should be good, as there is another issue in ios-sdk as well, here it is: https://github.com/watson-developer-cloud/ios-sdk/issues/221

Thank you.

**Comment by nacho4d** [comment]
@germanattanasio I modified (again) things to support iOS6 again (since some clients still require  it). I would like to close close this issue since target "watsonsdk" support iOS6 and "WatsonSDK" supports iOS8 and above.

 @mihui I haven't done anything about your last comment. I think it would be nice to implement that so I am making a new issue for it so we don't forget about it. See #39

> implement Text-to-Speech streaming (decode and play while downloading): currently it only decodes and plays the audio data after fully downloading it, if it's a long phrase, the user needs to wait for more time

**Comment by mihui** [comment]
Thanks @nacho4d
