### ISSUE TITLE
Implement Text-to-Speech streaming (decode and play while downloading)

### ISSUE THREAD

**Issue by nacho4d** [watson-developer-cloud/speech-ios-sdk#39]
Quoting a comment in #28 

> implement Text-to-Speech streaming (decode and play while downloading): currently it only decodes and plays the audio data after fully downloading it, if it's a long phrase, the user needs to wait for more time

**Comment by mihui** [comment]
As there is a new release of Watson Services, should we breakdown this task into:
- TTS streaming using WebSocket, this will implement WebSocket streaming and keep the current NSURLSessionDataTask implementation unchanged (I think it is not necessary to change it for supporting streaming)
- TTS real-time decoding, this will enable this SDK decoding the recorded data from both service and client side
