### ISSUE TITLE
WebSocket closed with reason[1000]: Manually terminating socket connection

### ISSUE THREAD

**Issue by AnilkumarRabhasa** [watson-developer-cloud/speech-ios-sdk#43]
I have integrated to my iOS app. Its working fine, but some times while converting speech to text/ Text to Speech, its showing following error.WebSocket closed with reason[1000]: Manually terminating socket connectionPlease help me how to fix this.

**Comment by germanattanasio** [comment]
Hey @AnilkumarRabhasa this project was deprecated. I suggest you try with the https://github.com/watson-developer-cloud/swift-sdk

Here is an example of how to use the swift-sdk with objective c https://github.com/watson-developer-cloud/simple-chat-objective-c

**Comment by AnilkumarRabhasa** [comment]
But, my project is in Objective-C, I can't use Swift now, can you help me this way?

**Comment by germanattanasio** [comment]
You can call a swift package from objective-c. That's what you should do.

**Comment by AnilkumarRabhasa** [comment]
@germanattanasio I integrated Swift SDK of Watson and doing bridging. But, really thanks so much for your quick response, here I got strucked, in Speech to text objective-c version we have following method

        [stt recognize:^(NSDictionary* res, NSError* err){
But, in Swift version where can I get, Can you please provide for Speech to Text Bridging with Objective-C like you provide link for Text To Speech following

https://github.com/watson-developer-cloud/swift-sdk/blob/master/docs/objective-c.md

Can you help on this

https://stackoverflow.com/questions/45814906/watson-swift-sdk-for-objective-c-bridging-for-speech-to-text
