### ISSUE TITLE
Improve the release/instructions

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/speech-ios-sdk#5]
Looks at Parse and Sense360 since developers were recommending those as good libraries to use as example.
In this case 3 developers were unable to follow the instructions and use the sdk in swift. 2 of them recommend to only write the sdks in swift since "Only old people write Objective-C"

**Comment by scprotz** [comment]
I have also followed the instructions to get this working in the latest XCode (7) and Swift (2.x) and have not been able to get the API up and running.  More detail would be appreciated.

**Comment by jpatrickmc** [comment]
Agree. At least providing the equivalent Swift code snippet for the existing Objective-C examples would be beneficial for us Swift Developers. Example - There is Objective-C code for Start and Stop Audio Transcription, but no Swift code.
