### ISSUE TITLE
Invalid credentials results in random "This doesn't look like a Opus file" error

### ISSUE THREAD

**Issue by duncsand** [watson-developer-cloud/speech-ios-sdk#8]
I get random "This doesn't look like a Opus file" errors when using text-to-speech. They seem to be based on the contents of the text being passed in. For example, "Welcome to your watson virtual assistant" gets an error, whereas "Welcome to your virtual assistant" works fine.
The errors appear to be coming from OpusHelper.m
This is on iOS9.

**Comment by scprotz** [comment]
I now am also receiving this bug.

**Comment by germanattanasio** [comment]
@daniel-bolanos do you have an idea of what this is ?

**Comment by scprotz** [comment]
I have an idea what mitt be causing it after some testing. Could be invalid json inbound. I'm going to try with some escaping of the question text and see if that works.

Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by duncsand** [comment]
I found out what was causing the issue. I was using my Bluemix login credentials to authenticate using basic auth. When I replaced those with the TTS Bluemix Service credentials shown in the Bluemix dashboard for the TSS service I'd provisioned, everything works fine.

**Comment by jsstylos** [comment]
Using incorrect credentials should generate a clear error message at the SDK level, so I think there's still a bug to fix here. (Renaming this issue to reflect that.)
